name: Deploy website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvcO -i"
          EXCLUDE: ".git"
          REMOTE_HOST: "sbrookfield.co.uk"
          REMOTE_PORT: 5388
          REMOTE_USER: "github"
          TARGET: "/var/www/html/website"